version: '3'
services:
  # pg:
  #   image: postgres:13
  #   container_name: pg
  #   restart: always
  #   command: postgres -c listen_addresses='*'
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d user"]
  #     interval: 10s
  #     timeout: 7s
  #     retries: 5
  #   ports:
  #     - 5432:5432
  #   environment:
  #       - POSTGRES_USER=postgres
  #       - POSTGRES_PASSWORD=postgres
  #       - POSTGRES_DB=user
  #   volumes:
  #     - pgdata:/data/postgres
      
  user-api:
    container_name: user-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    env_file:
      - .env
    # depends_on:
    #   pg:
    #     condition: service_healthy
    # links:
    #   - pg
    platform: "linux/amd64"
    volumes:
        - .:/usr/app
        - /usr/app/node_modules/

volumes:
  pgdata:
    driver: local