version: '3'
services:
  establishment-api:
    container_name: establishment-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    platform: "linux/amd64"
    env_file:
      - .env
    volumes:
        - .:/usr/app
        - /usr/app/node_modules/

volumes:
  pgdata:
    driver: local